language: elixir
elixir:
  - 1.4.5
otp_release:
  - 19.1
sudo: false
services:
  - redis-server
notifications:
  slack:
    rooms:
      - zombiiieeeesss:0Aaf3cWax9OKGd8En4ZJlBrF#ci
before_script:
  - mix do compile
  - export PATH=~/.mix:$PATH
  - mix do ecto.create, ecto.migrate
addons:
  postgresql: "9.4"
env:
  - MIX_ENV=test
script:
  - mix test
  - mix credo
