language: elixir
elixir:
  - 1.4.5
sudo: false # to use faster container based build environment
notifications:
  slack:
    rooms:
      - zombiiieeeesss:0Aaf3cWax9OKGd8En4ZJlBrF#ci
before_script:
  - mix do compile
  - export PATH=~/.mix:$PATH
  - mix do ecto.create, ecto.migrate
  - psql -U postgres -d db_test -c "create extension fuzzystrmatch;"
addons:
  postgresql: "9.4"
env:
  - MIX_ENV=test
