version: "3"

services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    volumes:
       - .:/app
    environment:
      - DB_USERNAME=postgres
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=outbreak_backend_dev
      - MIX_ENV=dev
      - VERK_REDIS_URL=redis://redis:6379
  redis:
    image: redis:3.2
    ports:
      - "6379"
  db:
    image: postgres:9.6
    ports:
      - "5432"
