FROM elixir:1.5
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app

COPY ./outbreak_backend_umbrella.tar.gz ./

RUN tar xfz outbreak_backend_umbrella.tar.gz

ENTRYPOINT ["bin/outbreak_backend_umbrella"]
