apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: outbreak-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: outbreak
    spec:
      containers:
        - name: outbreak
          image: outbreak:release
          ports:
            - containerPort: 8000
          args: ["foreground"]
          env:
            - name: HOST
              value: "example.com"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key_base
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: DB_NAME
              value: "outbreak_backend_prod"
            - name: DB_HOSTNAME
              value: "10.0.2.2"
